/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as PromoIndexRouteImport } from './routes/promo/index'
import { Route as CategoryIndexRouteImport } from './routes/category/index'
import { Route as PromoPromoIdRouteImport } from './routes/promo/$promoId'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as CategoryCategoryIdRouteImport } from './routes/category/$categoryId'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoIndexRoute = PromoIndexRouteImport.update({
  id: '/promo/',
  path: '/promo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoPromoIdRoute = PromoPromoIdRouteImport.update({
  id: '/promo/$promoId',
  path: '/promo/$promoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/offers': typeof OffersRoute
  '/stores': typeof StoresRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/promo/$promoId': typeof PromoPromoIdRoute
  '/category/': typeof CategoryIndexRoute
  '/promo/': typeof PromoIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/offers': typeof OffersRoute
  '/stores': typeof StoresRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/promo/$promoId': typeof PromoPromoIdRoute
  '/category': typeof CategoryIndexRoute
  '/promo': typeof PromoIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/offers': typeof OffersRoute
  '/stores': typeof StoresRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/promo/$promoId': typeof PromoPromoIdRoute
  '/category/': typeof CategoryIndexRoute
  '/promo/': typeof PromoIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/faq'
    | '/offers'
    | '/stores'
    | '/category/$categoryId'
    | '/product/$productId'
    | '/promo/$promoId'
    | '/category/'
    | '/promo/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/faq'
    | '/offers'
    | '/stores'
    | '/category/$categoryId'
    | '/product/$productId'
    | '/promo/$promoId'
    | '/category'
    | '/promo'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/faq'
    | '/offers'
    | '/stores'
    | '/category/$categoryId'
    | '/product/$productId'
    | '/promo/$promoId'
    | '/category/'
    | '/promo/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FaqRoute: typeof FaqRoute
  OffersRoute: typeof OffersRoute
  StoresRoute: typeof StoresRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  PromoPromoIdRoute: typeof PromoPromoIdRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  PromoIndexRoute: typeof PromoIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo/': {
      id: '/promo/'
      path: '/promo'
      fullPath: '/promo/'
      preLoaderRoute: typeof PromoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/': {
      id: '/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo/$promoId': {
      id: '/promo/$promoId'
      path: '/promo/$promoId'
      fullPath: '/promo/$promoId'
      preLoaderRoute: typeof PromoPromoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FaqRoute: FaqRoute,
  OffersRoute: OffersRoute,
  StoresRoute: StoresRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  PromoPromoIdRoute: PromoPromoIdRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  PromoIndexRoute: PromoIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
